array and list
* array is a data structure that stores a collection of elements of the same data type in contiguous memory locations. Each element in an array is identified by an index or a subscript.
* list is a data structure that stores a collection of elements of different data types.
* Unlike arrays, lists are dynamic and can grow or shrink in size during runtime
* Lists are used when the number of elements to be stored is not known beforehand or changes frequently
* All data that are used in the array should have the same dimension unlike a list 
 for example : [[2, 4], [5, 4]] and [[3], [5, 4, 5], [4, 8, 9, 12]]
* array has more speed than list (RAM should search in lots of place in memory to find a value but in array value save with good order)
* Big O in the list is 1


In [1]:
import numpy as np

In [2]:
list1 = [3, 3, 4, 6 ,9]
print(list1)

[3, 3, 4, 6, 9]


In [3]:
array = np.array(list1)
print(array)

[3 3 4 6 9]


We can see different between array and list print result (in 2 last cell)

In [4]:
print(type(list1))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


Array is kind of data structure with  iterable condition and index base 
point!:Access to every  array and listing houses is possible.  

In [5]:
print(list1[4])

9


In [6]:
print(array[4])

9


In [7]:
array.size

5

We can save on list in on house of list

In [8]:
list2 = [[4, 5, 6, 4], 4, 3, 2, 19]
print(list1)
print(len(list1))
print(list2)
print(len(list2))

[3, 3, 4, 6, 9]
5
[[4, 5, 6, 4], 4, 3, 2, 19]
5


In [9]:
list3 = [[3, 4, 5], [6, 7, 8], [5, 9, 12]]
print("We don't change member of list(The array and list have same member)")
print("The number of house we use for list are",len(list3))
array = np.array(list3)
print("The number of house we use for aray are",array.size)


We don't change member of list(The array and list have same member)
The number of house we use for list are 3
The number of house we use for aray are 9


In [10]:
for row in list3:
    print(row)

[3, 4, 5]
[6, 7, 8]
[5, 9, 12]


In [11]:
for row in array:
    print(row)

[3 4 5]
[6 7 8]
[ 5  9 12]


In [12]:
print(list3)
print(array)

[[3, 4, 5], [6, 7, 8], [5, 9, 12]]
[[ 3  4  5]
 [ 6  7  8]
 [ 5  9 12]]


If we have many type of data in array,au otomatically change member of array to one type

In [13]:
np.array(['s', 5, 45, True])

array(['s', '5', '45', 'True'], dtype='<U11')

In [14]:
print(type(array))

<class 'numpy.ndarray'>


In [24]:
list4 = [[3, 4, 5], [6, 7, 8], [7, 8, 9]]
array = np.array(list4)
print(array)

[[3 4 5]
 [6 7 8]
 [7 8 9]]


In [25]:
# dimension 2! 
array.ndim

2

In [27]:
# A real dimension 3
list5 = [[[3, 4, 5], [6, 7, 8], [7, 8, 9]]]
array = np.array(list5)
array.ndim

3

In [28]:
array.shape

(1, 3, 3)

.shape explanation
Dimension   line(row)   column

In [29]:
d, r, c = array.shape

In [35]:
print('DIMENSION :', d,
      ',ROW : ', r,
      ',COLUMN : ', c)

DIMENSION : 1 ,ROW :  3 ,COLUMN :  3


In [36]:
#The number of house in array
array.size

9

In [37]:
# We can't sum number to all member of list with same order as array
list4 + 2

TypeError: can only concatenate list (not "int") to list

In [38]:
array + 2

array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [26]:
l = [[[3, 4, 6], [5, 6, 7], [6, 3, 8]]]
# solution for array is :
for i in range(len(l)):
    l[i] += 2 

[[11, 12, 13, 14, 15]]


We can check the time of block

In [45]:
%%timeit
array + 2

816 ns ± 4.66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [46]:
lst = []
for i in range(10):
    lst.append(0)
print(lst)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [47]:
lst = [0 for i in range(10)]
print(lst)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [49]:
array = np.zeros(10)
print(array)
#float type

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
#int type 
array = np.zeros(10, np.int_)
print(array)

[0 0 0 0 0 0 0 0 0 0]


In [51]:
array = np.zeros((3, 4, 10), np.int_)
print(array)

[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]]


In [52]:
array = np.ones((3, 4, 10), np.int_)
print(array)

[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]]


ones and zeros are ready order for use,
but we can take other value

In [53]:
array = np.full((2, 3, 10), 4)
print(array)

[[[4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]]

 [[4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]]]


In [54]:
array = np.full((4, 3, 6), 72)
print(array)

[[[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]]


In [55]:
print(np.random.random(5))
# The value are between zero and one

[0.75024347 0.10884403 0.02538078 0.43181888 0.11297737]


In [56]:
print(np.random.random(5)*10)

[9.01931973 4.61316956 4.29574813 3.10692835 2.67265488]


we can change shape of array
but in list this work is so hard

In [58]:
array.reshape(18 ,4)

array([[72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72]])

In [59]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [61]:
np.arange(2, 200, 3.5)

array([  2. ,   5.5,   9. ,  12.5,  16. ,  19.5,  23. ,  26.5,  30. ,
        33.5,  37. ,  40.5,  44. ,  47.5,  51. ,  54.5,  58. ,  61.5,
        65. ,  68.5,  72. ,  75.5,  79. ,  82.5,  86. ,  89.5,  93. ,
        96.5, 100. , 103.5, 107. , 110.5, 114. , 117.5, 121. , 124.5,
       128. , 131.5, 135. , 138.5, 142. , 145.5, 149. , 152.5, 156. ,
       159.5, 163. , 166.5, 170. , 173.5, 177. , 180.5, 184. , 187.5,
       191. , 194.5, 198. ])