In [1]:
import numpy as np

In [46]:
a1 = [3 , 5, 5]
a2 = [5 , 4, 3]
a1+a2
# The second list add to the end of the first list

[3, 5, 5, 5, 4, 3]

In [47]:
b1 = np.array([3 ,5 ,5])
b2 = np.array([5 ,4 ,3])
b1+b2

array([8, 9, 8])

In [49]:
print(b1)
5 * b1
# All member of array will be offered 5 times

[3 5 5]


array([15, 25, 25])

In [50]:
b1.shape

(3,)

In [51]:
b1.ndim

1

In [52]:
b1.size

3

In [53]:
np.random.rand(2,3) * 2 + 5

array([[5.66018418, 6.04181258, 5.49359604],
       [6.25436555, 6.05720473, 5.95669533]])

In [2]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
a[0,0] = 5
a[2,1] = 3
a

array([[5., 0., 0.],
       [0., 0., 0.],
       [0., 3., 0.]])

In [7]:
b = np.ones((5,5))
b[1, :] = 5
b

array([[1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
b[:, 1] = 4
b[:, 2] = 7
b

array([[1., 4., 7., 1., 1.],
       [5., 4., 7., 5., 5.],
       [1., 4., 7., 1., 1.],
       [1., 4., 7., 1., 1.],
       [1., 4., 7., 1., 1.]])

In [10]:
b = np.ones((5, 5))
b[2][3] = 9
# in numpy library also we can use [line , column] for example
b[3,3] = 6
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# matrix with special dimension and random value for member
c = np.random.uniform(0,10,(5,5))
c = np.round(c)
# We use .round in numpy library for don't have float number
print(c)

[[0. 0. 1. 6. 0.]
 [6. 0. 9. 2. 7.]
 [2. 3. 9. 0. 5.]
 [4. 9. 4. 4. 9.]
 [7. 2. 8. 7. 2.]]


In [13]:
print(c.shape)

(5, 5)


In [15]:
print(b + c)
"""
if we don't use numpy library , this order has make new matrix with element of 
2 matrix , don't sum of them and we have one combination matrix of the element of 
2 matrices
"""

[[ 1.  1.  2.  7.  1.]
 [ 7.  1. 10.  3.  8.]
 [ 3.  4. 10.  9.  6.]
 [ 5. 10.  5. 10. 10.]
 [ 8.  3.  9.  8.  3.]]


"\nif we don't use numpy library , this order has make new matrix with element of \n2 matrix , don't sum of them and we have one combination matrix of the element of \n2 matrices\n"

In [16]:
print(b-c)

[[ 1.  1.  0. -5.  1.]
 [-5.  1. -8. -1. -6.]
 [-1. -2. -8.  9. -4.]
 [-3. -8. -3.  2. -8.]
 [-6. -1. -7. -6. -1.]]


In [18]:
print(b*c)
# this is not matrices multiplication 

[[ 0.  0.  1.  6.  0.]
 [ 6.  0.  9.  2.  7.]
 [ 2.  3.  9.  0.  5.]
 [ 4.  9.  4. 24.  9.]
 [ 7.  2.  8.  7.  2.]]


In [19]:
# matrices multiplication with this format
print(b.dot(c))

[[19. 14. 31. 19. 23.]
 [19. 14. 31. 19. 23.]
 [51. 86. 63. 51. 95.]
 [39. 59. 51. 39. 68.]
 [19. 14. 31. 19. 23.]]


In [20]:
# Horizontal stack 2 matrix
print(np.hstack((b,c)))

[[1. 1. 1. 1. 1. 0. 0. 1. 6. 0.]
 [1. 1. 1. 1. 1. 6. 0. 9. 2. 7.]
 [1. 1. 1. 9. 1. 2. 3. 9. 0. 5.]
 [1. 1. 1. 6. 1. 4. 9. 4. 4. 9.]
 [1. 1. 1. 1. 1. 7. 2. 8. 7. 2.]]


In [24]:
# Vertical stack 2 matrix
print("b matrix is :\n",b)
print("c matrix is :\n",c)
print("----------------------")
print('the result of vertical stack is \n',np.vstack((b,c)))

b matrix is :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]]
c matrix is :
 [[0. 0. 1. 6. 0.]
 [6. 0. 9. 2. 7.]
 [2. 3. 9. 0. 5.]
 [4. 9. 4. 4. 9.]
 [7. 2. 8. 7. 2.]]
----------------------
the result of vertical stack is 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 1. 6. 0.]
 [6. 0. 9. 2. 7.]
 [2. 3. 9. 0. 5.]
 [4. 9. 4. 4. 9.]
 [7. 2. 8. 7. 2.]]


In [29]:
print("matrix b is :\n", b)
print("matrix c is :\n", c)

matrix b is :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]]
matrix c is :
 [[0. 0. 1. 6. 0.]
 [6. 0. 9. 2. 7.]
 [2. 3. 9. 0. 5.]
 [4. 9. 4. 4. 9.]
 [7. 2. 8. 7. 2.]]


In [25]:
e=np.stack((b,c),axis=2)
print(e)

[[[1. 0.]
  [1. 0.]
  [1. 1.]
  [1. 6.]
  [1. 0.]]

 [[1. 6.]
  [1. 0.]
  [1. 9.]
  [1. 2.]
  [1. 7.]]

 [[1. 2.]
  [1. 3.]
  [1. 9.]
  [9. 0.]
  [1. 5.]]

 [[1. 4.]
  [1. 9.]
  [1. 4.]
  [6. 4.]
  [1. 9.]]

 [[1. 7.]
  [1. 2.]
  [1. 8.]
  [1. 7.]
  [1. 2.]]]


In [26]:
print(e.shape)

(5, 5, 2)


In [27]:

f=np.stack((b,c),axis=1)
print(f)
print(f.shape)

[[[1. 1. 1. 1. 1.]
  [0. 0. 1. 6. 0.]]

 [[1. 1. 1. 1. 1.]
  [6. 0. 9. 2. 7.]]

 [[1. 1. 1. 9. 1.]
  [2. 3. 9. 0. 5.]]

 [[1. 1. 1. 6. 1.]
  [4. 9. 4. 4. 9.]]

 [[1. 1. 1. 1. 1.]
  [7. 2. 8. 7. 2.]]]
(5, 2, 5)


In [30]:
g = np.arange(1,110,7)
print(g)

[  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]


In [31]:
# normal distribution
j = np.random.normal(55,1,(3,4))
# the element is more likely to be close to fifty-five
print(j)

[[54.84544443 55.32918087 54.99898358 54.39308855]
 [53.98578658 54.82051275 55.97039553 56.73152222]
 [54.04064733 54.90475563 54.01148919 55.72064656]]


In [32]:
print(np.round(j,1))

[[54.8 55.3 55.  54.4]
 [54.  54.8 56.  56.7]
 [54.  54.9 54.  55.7]]


In [33]:
print(np.round(j,2))

[[54.85 55.33 55.   54.39]
 [53.99 54.82 55.97 56.73]
 [54.04 54.9  54.01 55.72]]


In [34]:
print(np.round(j,3))

[[54.845 55.329 54.999 54.393]
 [53.986 54.821 55.97  56.732]
 [54.041 54.905 54.011 55.721]]


In [35]:
print(np.round(j,-1))

[[50. 60. 50. 50.]
 [50. 50. 60. 60.]
 [50. 50. 50. 60.]]


In [36]:
print(np.min(j))

53.985786580249275


In [37]:
print(np.max(j))

56.73152221867863


In [38]:
print(np.sum(j))

659.7524532254889


In [39]:
print(np.mean(j))

54.97937110212408


In [40]:
print(np.median(j))

54.87510002973528


In [41]:
print(np.max(j,axis=0))
# axis = 1 is for column

[54.84544443 55.32918087 55.97039553 56.73152222]


In [42]:
print(np.max(j,axis=1))
# axis = 1 is for line 

[55.32918087 56.73152222 55.72064656]


In [43]:
print(np.sum(j,axis=0))

[162.87187834 165.05444925 164.98086831 166.84525733]


In [44]:
print(np.sum(j,axis=1))

[219.56669744 221.50821708 218.6775387 ]
