array and list
* array is a data structure that stores a collection of elements of the same data type in contiguous memory locations. Each element in an array is identified by an index or a subscript.
* list is a data structure that stores a collection of elements of different data types.
* Unlike arrays, lists are dynamic and can grow or shrink in size during runtime
* Lists are used when the number of elements to be stored is not known beforehand or changes frequently
* All data that are used in the array should have the same dimension unlike a list 
 for example : [[2, 4], [5, 4]] and [[3], [5, 4, 5], [4, 8, 9, 12]]
* array has more speed than list (RAM should search in lots of place in memory to find a value but in array value save with good order)
* Big O in the list is 1


In [7]:
import numpy as np

In [8]:
list1 = [3, 3, 4, 6 ,9]
print(list1)

[3, 3, 4, 6, 9]


In [9]:
array = np.array(list1)
print(array)

[3 3 4 6 9]


We can see different between array and list print result (in 2 last cell)

In [10]:
print(type(list1))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


Array is kind of data structure with  iterable condition and index base 
point!:Access to every  array and listing houses is possible.  

In [11]:
print(list1[4])

9


In [12]:
print(array[4])

9


In [13]:
array.size

5

We can save on list in on house of list

In [14]:
list2 = [[4, 5, 6, 4], 4, 3, 2, 19]
print(list1)
print(len(list1))
print(list2)
print(len(list2))

[3, 3, 4, 6, 9]
5
[[4, 5, 6, 4], 4, 3, 2, 19]
5


In [15]:
list3 = [[3, 4, 5], [6, 7, 8], [5, 9, 12]]
print("We don't change member of list(The array and list have same member)")
print("The number of house we use for list are",len(list3))
array = np.array(list3)
print("The number of house we use for aray are",array.size)


We don't change member of list(The array and list have same member)
The number of house we use for list are 3
The number of house we use for aray are 9


In [16]:
for row in list3:
    print(row)

[3, 4, 5]
[6, 7, 8]
[5, 9, 12]


In [17]:
for row in array:
    print(row)

[3 4 5]
[6 7 8]
[ 5  9 12]


In [18]:
print(list3)
print(array)

[[3, 4, 5], [6, 7, 8], [5, 9, 12]]
[[ 3  4  5]
 [ 6  7  8]
 [ 5  9 12]]


If we have many type of data in array,au otomatically change member of array to one type

In [19]:
np.array(['s', 5, 45, True])

array(['s', '5', '45', 'True'], dtype='<U11')

In [20]:
print(type(array))

<class 'numpy.ndarray'>


In [21]:
list4 = [[3, 4, 5], [6, 7, 8], [7, 8, 9]]
array = np.array(list4)
print(array)

[[3 4 5]
 [6 7 8]
 [7 8 9]]


In [22]:
# dimension 2! 
array.ndim

2

In [23]:
# A real dimension 3
list5 = [[[3, 4, 5], [6, 7, 8], [7, 8, 9]]]
array = np.array(list5)
array.ndim

3

In [24]:
array.shape

(1, 3, 3)

.shape explanation
Dimension   line(row)   column

In [25]:
d, r, c = array.shape

In [26]:
print('DIMENSION :', d,
      ',ROW : ', r,
      ',COLUMN : ', c)

DIMENSION : 1 ,ROW :  3 ,COLUMN :  3


In [27]:
#The number of house in array
array.size

9

In [28]:
# We can't sum number to all member of list with same order as array
list4 + 2

TypeError: can only concatenate list (not "int") to list

In [29]:
# Our solution for list is:
def add(lst):
    if isinstance(lst, list):
        for i in range(len(lst)):
            lst[i] = add(lst[i])
        return lst
    else:
        return lst + 10
list5 = [[[3, 4, 6], [5, 6, 7], [6, 7, 8]]]
result = add(list5)
print(result)

[[[13, 14, 16], [15, 16, 17], [16, 17, 18]]]


In [48]:
l = [3, 4, 6]
new_list = [x + 10 for x in l]
l.clear()
l.append(new_list)
print(l)

[[13, 14, 16]]


In [31]:
array + 2

array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [32]:
l = [[[3, 4, 6], [5, 6, 7], [6, 3, 8]]]
# solution for array is :
for i in range(len(l)):
    l[i] += 2 

TypeError: 'int' object is not iterable

We can check the time of block

In [33]:
%%timeit
array + 2

1.09 µs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
lst = []
for i in range(10):
    lst.append(0)
print(lst)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [35]:
lst = [0 for i in range(10)]
print(lst)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [36]:
array = np.zeros(10)
print(array)
#float type

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
#int type 
array = np.zeros(10, np.int_)
print(array)

[0 0 0 0 0 0 0 0 0 0]


In [38]:
array = np.zeros((3, 4, 10), np.int_)
print(array)

[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]]


In [39]:
array = np.ones((3, 4, 10), np.int_)
print(array)

[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]]


ones and zeros are ready order for use,
but we can take other value

In [40]:
array = np.full((2, 3, 10), 4)
print(array)

[[[4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]]

 [[4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]
  [4 4 4 4 4 4 4 4 4 4]]]


In [41]:
array = np.full((4, 3, 6), 72)
print(array)

[[[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]

 [[72 72 72 72 72 72]
  [72 72 72 72 72 72]
  [72 72 72 72 72 72]]]


In [42]:
print(np.random.random(5))
# The value are between zero and one

[0.86427483 0.24127807 0.84952516 0.1352888  0.10175586]


In [43]:
print(np.random.random(5)*10)

[4.4040321  7.64713436 9.92232655 1.43407982 2.41235361]


we can change shape of array
but in list this work is so hard

In [44]:
array.reshape(18 ,4)

array([[72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72]])

In [45]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [46]:
np.arange(2, 200, 3.5)

array([  2. ,   5.5,   9. ,  12.5,  16. ,  19.5,  23. ,  26.5,  30. ,
        33.5,  37. ,  40.5,  44. ,  47.5,  51. ,  54.5,  58. ,  61.5,
        65. ,  68.5,  72. ,  75.5,  79. ,  82.5,  86. ,  89.5,  93. ,
        96.5, 100. , 103.5, 107. , 110.5, 114. , 117.5, 121. , 124.5,
       128. , 131.5, 135. , 138.5, 142. , 145.5, 149. , 152.5, 156. ,
       159.5, 163. , 166.5, 170. , 173.5, 177. , 180.5, 184. , 187.5,
       191. , 194.5, 198. ])